### PR TITLE
Fix the issue for resource section

### LINKED ISSUE #17: Some problems with the Resources module
image

There needs to be some spacing between the title and the content to make them look separate. Please refer to the design drawing for details.

Also, there are some issues with the width at 2560, I have added references for each resolution
image

### PR DESCRIPTION
**Pull request by hamidroohi71**
This PR resolves the issue #17 for resource section

### CODE REVIEW

**Comment by boundless-forest** [comment]
image

Please format these lines better. Suggest formatting  it with a specific tool in js, or solidity.

**Comment by boundless-forest** [comment]
image

This one looks great, some of them can be updated to a better version:

image

Missing License for this:
image

Please check all the code snippets and make sure they are formatted properly.

**Comment by hackfisher** [comment]
Why there is no file  changes?

**Comment by boundless-forest** [comment]
> Why there is no file changes?

This changes have been included the previous PR https://github.com/msgport/home/pull/26 and merged, let's close this and create a issue for the review comments.

**Pull request closed without merging**
