### PR TITLE
Msgport home page

### PR DESCRIPTION
**Pull request by hamidroohi71**
This PR aims to fix the first iteration issues of the homepage for msgport!

### CODE REVIEW

**Comment by boundless-forest** [comment]
It seems that many links are unclickable. Why?

**Comment by boundless-forest** [comment]
It should be Msgport instead of MSGPort.

**Comment by hackfisher** [comment]
@hamidroohi71 Wha't the difference between this PR and https://github.com/msgport/home/pull/8, can we close that one if this is merged?

**Comment by hamidroohi71** [comment]
> 
> 
> It should be Msgport instead of MSGPort.

I fixed it

**Comment by hamidroohi71** [comment]
> @hamidroohi71 Wha't the difference between this PR and #8, can we close that one if this is merged?

It is a draft this version is complete. We can close it

**Comment by hackfisher** [comment]
> > @hamidroohi71 Wha't the difference between this PR and #8, can we close that one if this is merged?
> 
> Where can I find the links? There is no link in Figma

I will fix the links, wait a moment.

**Comment by hamidroohi71** [comment]
> It seems that many links are unclickable. Why?

How can I find the links? I do not have any references in FIgma

**Comment by hamidroohi71** [comment]
About favicon: I put it in the local version but after making the Pr is does not show up.

**Comment by hackfisher** [comment]
Get Started: https://docs.msgport.xyz/build/tutorial/remix-demo/


xacount view use case in docs: https://docs.msgport.xyz/learn/use-cases/xaccount/
order xclear view use case in docs:  https://docs.msgport.xyz/learn/use-cases/order-xclearing/

image


https://github.com/msgport
https://scan.msgport.xyz/
https://docs.msgport.xyz/

image


xapi-dao: https://github.com/xapi-box

@hamidroohi71 Here are some of the links, for the left, would you please provide place holder, thanks.

**Comment by hackfisher** [comment]
image

https://t.me/msgport_support

image

https://t.me/msgport

Hide the twitter for now.

**Comment by hamidroohi71** [comment]
All done

**Review by hackfisher — APPROVED** [review]

**Pull request merged**
